/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Kasus;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        //nilai yang dikembailkan tidak null
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
