/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasusDB;
import java.sql.*;

public class App {
 

    public static void main(String[] args) {
        
        //membaut sebuah koneksi
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/movie_rental","root","root");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select full_names, movies_rented from rented join membership where rented.membership_id = membership.membership_id");
            
            while (rs.next()) {
                System.out.println(rs.getString("full_names")+rs.getString("movies_rented"));   
                
            }
            rs.first();
            System.out.println(rs.getString(1));   
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
}
